spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: 
    driver-class-name: org.h2.Driver

jwt:
  secret: 526753878GQ6+556A586E327kE5D+hlIlStxSSm404E637z32MPi+W7O53ZsJa/0XdFG+MIA9235
  expiration:
    accessToken: 5000
    refreshToken: 360000