## order API Test

### 주문등록
POST http://localhost:8080/api/orders
Content-Type: application/json

{
    "accountId" : "jinho",
    "orderItem" : [
        {
            "productId": 1,
            "quantity": 1
        },
        {
            "productId": 2,
            "quantity": 3
        }
    ],
    "address": {
        "name": "한진호",
        "phoneNumber": "01026040547",
        "postalCode": "123456",
        "address1": "경기도 성남시",
        "address2": "와이즈넛"
    }
}
