## product API Test

### 상품등록
POST http://localhost:8080/product
Content-Type: application/json

{
  "name": "MacBook air",
  "price": 1390000
}

### 상품리스트 조회
GET http://localhost:8080/product?page=1&size=10


### 상품 조회
GET http://localhost:8080/product/1
#상품 거절됨, 승인대기 상태가 확인되어야 할 듯

### 상품 승인
PUT http://localhost:8080/product/approve/allow?id=2

### 상품 거절
PUT http://localhost:8080/product/approve/deny?id=2

### 상품 승인 재요청 (거절상태일 경우)
POST http://localhost:8080/product/2
